name: Rails Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Run Elasticsearch
        uses: sanfrecce-osaka/elasticsearch-with-plugins-action@main
        with:
          stack-version: 7.6.0
          plugins: |
            analysis-kuromoji
      - name: Build and test
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libsqlite3-dev
          bundle install --jobs 4 --retry 3
          bin/rails db:create
          bin/rails db:migrate
          bin/yarn install
          bin/rails test
          bin/rails test:system
